agent-instrumentation-properties:
  preloadClasses:
  noTransformClass: com.cisco.mtagent,com.cisco.argento,com.singularity,com.appdynamics
  noTransformLoaderClassName: com.cisco.mtagent,com.cisco.argento,com.singularity,com.appdynamics
  noOsgiBootDelegationSet: was.install.root
  noTransformThreadName:
  classReviewInterval: 10
  # Instrument Anonymous Classes - this is Experimental
  useAnonymousClassTransform: false
  trackReviewedClasses: false
  # Force an immediate retransform to get Class Object - this is Experimental
  useInitialTransform: false
  showJMX: false
  # Clear ctClassCache after 3 minutes
  ctClassCacheClearSeconds: 180

agent-misc-settings:
  sslProtocol: TLSV1.2
  version: 23.11.0-1173


agent-logging:
  initialMaxLogSize: 2000000
  maxLogSize: 1000000
  maxLogs: 10
  maxLogMsgsPerSecond: 100
  maxLoggingQueueSize: 1000
  showDecryptedFiles: true
  useLocking: false
  # Need double slash for escaping
  agent-masking-pii-list-default:

agent-reflection-list:


#ENCRYPT


agent-internal-handlers:
  #
  # Async Instrumentation - all disabled right now
  #
    - class: java.lang.Runnable
      method: run
      handler: com.cisco.mtagent.async.AsynchCorrelationInternalHandler
      interface: true
      excludeclass: java.util.concurrent.ThreadPoolExecutor$Worker,java.lang.Thread,java.util.concurrent.FutureTask
      active: false

    - class: java.util.concurrent.Callable
      method: call
      handler: com.cisco.mtagent.async.AsynchCorrelationInternalHandler
      interface: true
      excludeclass: java.util.concurrent.Executors$RunnableAdapter
      active: false

    - class: java.lang.Thread
      method: start
      handler: com.cisco.mtagent.async.AsynchCorrelationInternalHandler
      active: false

    - class: java.util.concurrent.ThreadPoolExecutor
      method: execute
      handler: com.cisco.mtagent.async.AsynchCorrelationInternalHandler
      interface: true
      active: false

    - class: java.util.concurrent.AbstractExecutorService
      method: submit
      handler: com.cisco.mtagent.async.AsynchCorrelationInternalHandler
      interface: true
      active: false

  #
  # Proxy and Delegate
  #

    - proxy: true
      handler: com.cisco.mtagent.instrumentation.InstrumentationClassLoadingProxyInternalHandler
      active: true


  #
  # OTEL Instrumentation
  #

    - class: io.opentelemetry.api.trace.Span
      method: end
      handler: com.cisco.mtagent.instrumentation.InstrumentationOTELInternalHandler
      interface: true
      catch: false
      exit: false
      condition: multi.tenant.agent.allow.otel.instrumentation

    - class:  io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.Span
      method:  end
      handler: com.cisco.mtagent.instrumentation.InstrumentationOTELInternalHandler
      interface: true
      catch: false
      exit: false
      condition: multi.tenant.agent.allow.otel.instrumentation

    - class: io.opentelemetry.api.trace.Span
      method: startSpan
      handler: com.cisco.mtagent.instrumentation.InstrumentationOTELInternalHandler
      interface: true
      catch: false
      entry: false
      condition: multi.tenant.agent.allow.otel.instrumentation

    - class:  io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.Span
      method:  startSpan
      handler: com.cisco.mtagent.instrumentation.InstrumentationOTELInternalHandler
      interface: true
      catch: false
      entry: false
      condition: multi.tenant.agent.allow.otel.instrumentation


#END-ENCRYPTION

load-java-agent:
    - jar: ../../oss-java-agent/opentelemetry-javaagent.jar
      properties: -Dotel.resource.attributes=service.name=oss-agent-service -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans
      condition: multi.tenant.agent.launch.oss.agent

